name: Build and Release k-NN
on:
  push:
    tags:
      - v*

jobs:
  Build-k-NN:
    strategy:
      matrix:
        java: [14]
        compiler: [g++-5]

    name: Build and Release k-NN Plugin
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v2

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build and ship library artifacts
        env:
          CXX: ${{ matrix.compiler }}
        run: |
            cd jni
            cmake .
            make package

            artifact=`ls release/*.so`
            rpm_artifact=`ls packages/*.rpm`
            deb_artifact=`ls packages/*.deb`

            aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/opendistro-knn/
            aws s3 cp $rpm_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/rpms/opendistro-knn/
            aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-knn/
            aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/*"

      - name: Build and ship plugin artifacts
        run: |
          ./gradlew buildPackages --console=plain -Dbuild.snapshot=false
          artifact=`ls build/distributions/*.zip`
          rpm_artifact=`ls build/distributions/*.rpm`
          deb_artifact=`ls build/distributions/*.deb`

          aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/opendistro-knn/
          aws s3 cp $rpm_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/rpms/opendistro-knn/
          aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-knn/
          aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/*"
